### ISSUE TITLE
Product image previews do not show at checkout

### ISSUE THREAD

**Issue by eufandem** [chec/commercejs-nextjs-vercel#5]
<img width="560" alt="Screen Shot 2020-10-01 at 3 06 05 PM" src="https://user-images.githubusercontent.com/29156467/94868396-f6f52b00-03f7-11eb-858a-1fd34e9ef2c8.png">

**Comment by fernandoamz** [comment]
@eufandem, @jaepass May I review this bug?

**Comment by eufandem** [comment]
@fernandoamz Please do!

**Comment by fernandoamz** [comment]
@eufandem, Please assign me it. I will make the pull request as soon as possible.

**Comment by fernandoamz** [comment]
@eufandem Please review, I found the issue the solution is on this PR: https://github.com/chec/commercejs-nextjs-vercel/pull/6

**Comment by eufandem** [comment]
This issue is still persistent

**Comment by fernandoamz** [comment]
@eufandem, May I take a look again?

**Comment by robbieaverill** [comment]
@eufandem where are you seeing it? It looks good to me locally using the Chec API key in the project's example config:
![image](https://user-images.githubusercontent.com/5170590/96043363-b0ee8d00-0e23-11eb-87b5-399351fd0793.png)

**Comment by eufandem** [comment]
https://commercejs-nextjs-vercel.now.sh/ @robbieaverill

**Comment by robbieaverill** [comment]
Must be something wrong with the Vercel integration. The latest deployment is https://commercejs-nextjs-vercel-alxksmk4p.vercel.app/ and that looks fine.

The origin for this repo on Vercel is https://commercejs-nextjs-vercel-orcin.vercel.app

**Comment by eufandem** [comment]
Yeah I think so as there are some updates I pushed to the /about page last week that arent showing up. @jaepass can you weigh in here please

**Comment by fernandoamz** [comment]
@eufandem, I reviewed locally and it is showing the image

**Comment by eufandem** [comment]
Thanks @fernandoamz, I'll update the "view live demo" links in the repo to https://commercejs-nextjs-vercel-orcin.vercel.app

**Comment by robbieaverill** [comment]
New origin URL is https://commercejs-nextjs-vercel.vercel.app/ @eufandem

**Comment by robbieaverill** [comment]
I've assigned it the original URL (https://commercejs-nextjs-vercel.now.sh/) as well

**Comment by jaepass** [comment]
thanks for ironing this out, was deployed from my personal vercel acc originally before we opened a Chec one.
